from enum import Enum

class EnumResponseCode(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    SERVER_ERROR = 'SERVER_ERROR'

class EnumResponseStatusCode(Enum):
    CREATED_SUCCESSFULLY = 'CREATED_SUCCESSFULLY'
    RECOVERED_SUCCESSFULLY = 'RECOVERED_SUCCESSFULLY'
    SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG'
    EXISTS_ALREADY = 'EXISTS_ALREADY'
    ACCOUNT_DELETED = 'ACCOUNT_DELETED'
    NOT_FOUND = 'NOT_FOUND'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    UNAUTHORIZED='UNAUTHORIZED'
    NOT_ALLOWED = 'NOT_ALLOWED'
    NO_ACCESS_TOKEN='NO_ACCESS_TOKEN'
    CANNOT_DECODE_TOKEN = 'CANNOT_DECODE_TOKEN'
